import { useEffect, useState } from 'react';
import { ArrowRight, Sparkles, Coffee, Moon, Zap, Car, Leaf, Laptop, LoaderCircle, Headphones, Radio, Disc3, Plus, ArrowUpRight } from 'lucide-react';
import { PageHeading, SectionHeading, PlaylistCard, SkeletonCards, ErrorBox, Artwork, CuratorBadge } from './components';
import { defaults, titleCase } from './api';
import { PlaylistDialog } from './SongActions';

const vibes = [
  { label: 'Deep focus', note: 'Get in the zone', icon: Laptop, color: 'violet', prompt: 'Deep focus for a coding session: instrumental lo-fi and ambient, steady energy, no distracting vocals.' },
  { label: 'Slow mornings', note: 'Ease into the day', icon: Coffee, color: 'peach', prompt: 'A slow Sunday morning with coffee. Warm acoustic and indie, easygoing and a little nostalgic.' },
  { label: 'After hours', note: 'Stay a little longer', icon: Moon, color: 'blue', prompt: 'Late night unwinding, dreamy atmospheric electronic and indie music, calm but not sleepy.' },
  { label: 'Full energy', note: 'Find your second wind', icon: Zap, color: 'lime', prompt: 'A high energy workout playlist with driving beats and uplifting electronic music. Keep the momentum going.' },
  { label: 'Open roads', note: 'Take the long way', icon: Car, color: 'rose', prompt: 'A long scenic road trip with friends, upbeat indie rock and pop, singalong and feel-good.' },
  { label: 'Just breathe', note: 'Make a little space', icon: Leaf, color: 'mint', prompt: 'Gentle music to relax and clear my head. Peaceful ambient and soft instrumental, very low energy.' },
];

export function MoodComposer({ draft, setDraft, onGenerate, generating, error, preferenceSize, expanded = false }) {
  const [size, setSize] = useState(preferenceSize || defaults.playlist_size);
  useEffect(() => { setSize(preferenceSize || defaults.playlist_size); }, [preferenceSize]);
  return <form className={`mood-composer ripple-object ${expanded ? 'expanded' : ''}`} onSubmit={event => { event.preventDefault(); onGenerate(draft, size); }}><div className="composer-label"><span className="ripple-text"><Sparkles size={17} />{expanded ? 'LET’S SET THE SCENE' : 'DESCRIBE YOUR MOMENT'}</span><span className="ripple-text">There’s no wrong answer.</span></div><label className="sr-only" htmlFor="mood-prompt">Describe your mood or activity</label><textarea id="mood-prompt" required minLength={3} maxLength={2000} value={draft} onChange={event => setDraft(event.target.value)} placeholder="It’s a rainy evening. I’m getting some work done, but my mind’s somewhere else. Something mellow, a little indie…" rows={expanded ? 5 : 3} /><div className="composer-footer"><label className="size-select"><Disc3 size={15} /><select aria-label="Number of tracks" value={size} onChange={event => setSize(Number(event.target.value))}>{Array.from({ length: 11 }, (_, n) => n + 10).map(n => <option value={n} key={n}>{n} tracks</option>)}</select></label><button className="button primary ripple-object" disabled={generating || draft.trim().length < 3}>{generating ? <LoaderCircle size={17} className="spin" /> : <Sparkles size={17} />}{generating ? 'Finding your sound…' : 'Build mood queue'}{!generating && <ArrowRight size={16} />}</button></div><ErrorBox error={error} />{generating && <div className="generation-note" role="status"><span className="pulse-dot" />Understanding your mood and finding matching tracks. Your moment is worth a thoughtful mix.</div>}</form>;
}

export function Dashboard({ queue, notify, user, playlists, loading, error, retry, draft, setDraft, onGenerate, generating, generateError, navigate, onOpen, health }) {
  const [creating, setCreating] = useState(false);
  const firstName = user.name?.split(' ')[0] || 'friend';
  const hour = new Date().getHours(); const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening';
  const recent = playlists.slice(0, 4);
  const counts = playlists.reduce((out, p) => { const mood = p.profile?.primary_mood; if (mood) out[mood] = (out[mood] || 0) + 1; return out; }, {});
  const topMood = Object.entries(counts).sort((a, b) => b[1] - a[1])[0];
  return <div className="dashboard-page"><PageHeading eyebrow="YOUR DAILY DOSE OF GOOD SOUND" title={`${greeting}, ${firstName}.`} description="Let’s find a little music that feels like you." /><section className="dashboard-hero ripple-object"><div className="hero-text"><CuratorBadge /><h2 className="ripple-text">Your mood changes.<br />Your <em>queue follows.</em></h2><p className="ripple-text">Tell us what’s on your mind.<br />We’ll take care of what’s in your headphones.</p><div className="hero-bottom"><span className="hero-mini-lines"><i /><i /><i /><i /><i /></span><span className="ripple-text">LESS SCROLLING. MORE FEELING.</span></div></div><Artwork seed="dashboard-mood" className="dashboard-art"><span className="art-poster-small">TUNE INTO<br />YOURSELF.</span><div className="poster-ring ring-a" /><div className="poster-ring ring-b" /><span className="art-poster-script">a good<br />kind of lost.</span><span className="art-poster-bottom">SOULTUNE SESSIONS — VOL. 01</span></Artwork></section><MoodComposer draft={draft} setDraft={setDraft} onGenerate={onGenerate} generating={generating} error={generateError} preferenceSize={user.preferences?.playlist_size} />
    <section className="section-block">{queue?.tracks?.length > 0 && <button className="button secondary ripple-object" onClick={() => onOpen(queue.id)}><PlayQueueIcon />Continue your mood queue · {queue.tracks.length} songs</button>}<SectionHeading title="Or, start with a feeling" subtitle="A little inspiration for wherever you are." /><div className="quick-vibes">{vibes.map(({ icon: Icon, ...vibe }) => <button className={`vibe-card ripple-object ${vibe.color}`} key={vibe.label} onClick={() => { setDraft(vibe.prompt); document.getElementById('mood-prompt')?.focus(); }}><span><Icon size={20} /></span><strong className="ripple-text">{vibe.label}</strong><small>{vibe.note}</small></button>)}</div></section>
    <section className="section-block"><SectionHeading title="Your playlists" subtitle="The collections you created and the songs you chose." action={() => navigate('history')} actionLabel="View all" /><ErrorBox error={error} retry={retry} />{loading ? <SkeletonCards /> : recent.length ? <div className="playlist-grid">{recent.map(p => <PlaylistCard key={p.id} playlist={p} onOpen={onOpen} />)}</div> : <div className="first-playlist ripple-object"><span className="first-playlist-icon"><Disc3 size={31} /></span><div><h3 className="ripple-text">Your playlists start with you.</h3><p>Mood requests update your queue. Create a named playlist to keep a collection of songs.</p></div><button className="icon-button" aria-label="Create your first playlist" onClick={() => setCreating(true)}><ArrowUpRight size={22} /></button></div>}</section>
    <div className="dashboard-notes"><div className="note-card ripple-object"><span className="note-icon"><Headphones size={20} /></span><div><span className="eyebrow">YOUR MUSIC, ALWAYS CLOSE</span><h3 className="ripple-text">A collection that travels offline.</h3><p>{health?.local_track_count ? `${health.local_track_count} local tracks are ready for when a preview can't play.` : 'Add your downloaded songs to fallback_songs. They’re your backup when a preview can’t play.'}</p><button className="text-button" onClick={() => navigate('library')}>Open local library <ArrowRight size={14} /></button></div></div><div className="note-card ripple-object"><span className="note-icon peach"><Radio size={20} /></span><div><span className="eyebrow">A LITTLE SELF-DISCOVERY</span><h3 className="ripple-text">{topMood ? `Lately, you’re feeling ${titleCase(topMood[0]).toLowerCase()}.` : 'What does your mood sound like?'}</h3><p>{playlists.length ? `${playlists.length} playlist${playlists.length === 1 ? '' : 's'}, each a snapshot of a moment. See the sounds you keep coming back to.` : 'As you create playlists, discover the moods, genres, and rhythms you gravitate toward.'}</p><button className="text-button" onClick={() => navigate('analytics')}>Explore your listening DNA <ArrowRight size={14} /></button></div></div></div>
  {creating && <PlaylistDialog open onClose={() => setCreating(false)} onCreated={playlist => onOpen(playlist.id)} notify={notify} />}</div>;
}

function PlayQueueIcon() { return <Headphones size={17} />; }

export function CreatePage(props) {
  return <div className="create-page"><PageHeading eyebrow="MAKE ROOM FOR A NEW MOOD" title="A queue for this moment." description="Describe your mood to replace your current queue. Your handpicked playlists stay unchanged." /><MoodComposer {...props} expanded />{props.queue?.tracks?.length > 0 && <button className="button secondary queue-resume" onClick={() => props.onOpen(props.queue.id)}><Headphones size={17} />Continue current queue · {props.queue.tracks.length} songs</button>}<div className="prompt-help"><span>Try adding</span>{['A mood', 'An activity', 'Your energy', 'A genre', 'An era'].map(s => <span className="chip" key={s}>{s}</span>)}</div><section className="section-block"><SectionHeading title="A few places to begin" subtitle="Borrow a moment. Then make it your own." /><div className="example-grid">{vibes.slice(0, 3).map((vibe, n) => <button key={vibe.label} className="example-card" onClick={() => { props.setDraft(vibe.prompt); document.getElementById('mood-prompt')?.focus(); }}><span className="eyebrow">0{n + 1} / {vibe.label}</span><p>“{vibe.prompt}”</p><ArrowUpRight size={19} /></button>)}</div></section></div>;
}
